---
common_pkgs_pacman:
  install:
    - base-devel
    - python-pip
    - python-setuptools
    - python-yaml
    - openssl
    - libffi
    - systemd
    - systemd-sysvcompat
    - iproute2
    - ansible
  remove: []
  remove_regex: []
  remove_modified_configs: false
